env = XCURSOR_THEME,phinger-cursors-dark
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,phinger-cursors-dark
env = HYPRCURSOR_SIZE,24

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

env = QT_QPA_PLATFORMTHEME,qt6ct
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps

ecosystem {
    enforce_permissions = false
    no_update_news = true
    no_donation_nag = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    initial_workspace_tracking=1
    disable_watchdog_warning = true
}

monitor= desc:ASUSTek COMPUTER INC XG27ACS T1LMTF008132, 2560x1440@180.00Hz, 0x0, 1, cm, auto, vrr, 3

input {
    kb_layout = it
    kb_variant =
    kb_model = pc104
    kb_options = # caps:swapescape
    kb_rules =

    numlock_by_default = true

    repeat_rate = 30
    repeat_delay = 250

    follow_mouse = 1
    accel_profile = flat
    sensitivity = 0
}
