# Nordic Colorscheme for Kitty.
# Based on https://github.com/AlexvZyl/nordic.nvim.
# Author: @AlexvZyl.

# white0_reduce_blue
foreground            #C0C8D8
# gray0
background            #242933
# white0_reduce_blue
selection_foreground  #C0C8D8
# gray1
selection_background  #2E3440
# blue2
url_color             #88C0D0
# white0_reduce_blue
cursor                #C0C8D8

# black1
color0   #191D24
# gray2
color8   #3B4252

# red_base
color1   #BF616A
# red_bright
color9   #C5727A

# green_base
color2   #A3BE8C
# green_bright
color10  #B1C89D

# yellow_base
color3   #EBCB8B
# yellow_bright
color11  #EFD49F

# blue0
color4  #5E81AC
# blue2
color12 #88C0D0

# magenta_base
color5   #B48EAD
# magenta_bright
color13  #BE9DB8

# cyan_base
color6   #8FBCBB
# cyan_bright
color14  #9FC6C5

# white0_reduce_blue
color7   #C0C8D8
# white1
color15  #D8DEE9
