server:
    server-count: 1
    ip-address: 127.0.0.1
    port: 53530
    do-ip4: yes
    hide-version: yes
    identity: "Home network authoritative DNS"
    zonesdir: "/etc/nsd"

remote-control:
    control-enable: yes
    control-interface: "127.0.0.1"
    control-port: 8952
    server-key-file: "/etc/nsd/nsd_server.key"
    server-cert-file: "/etc/nsd/nsd_server.pem"
    control-key-file: "/etc/nsd/nsd_control.key"
    control-cert-file: "/etc/nsd/nsd_control.pem"

key:
    name: "unbound-nsd"
    algorithm: hmac-md5
    secret: "i8SuGfZ3PbkOObI04DYlTxcc6+FS3oPRXnnAMBVVD5I="

zone:
    name: "unbound-nsd.dns"
    zonefile: "/etc/nsd/unbound-nsd.dns.zone"
