[Service]
; DynamicUser=true
IPAddressDeny=any
NoNewPrivileges=true
PrivateNetwork=true
PrivateTmp=true
ProtectControlGroups=yes
ProtectHome=yes
ProtectHostname=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectSystem=yes
; SystemCallFilter=@raw-io
; SystemCallFilter=@resources
; AmbientCapabilities=CAP_SYS_RAWIO
; CapabilityBoundingSet=CAP_SYS_RAWIO
