$black0 = rgb(191D24)
$black1 = rgb(1E222A)
$black2 = rgb(222630)

$gray0 = rgb(242933) # bg
$gray1 = rgb(2E3440)
$gray2 = rgb(3B4252)
$gray3 = rgb(434C5E)
$gray4 = rgb(4C566A)
$gray5 = rgb(60728A)

$white0_normal = rgb(BBC3D4) # fg
$white0_reduce_blue = rgb(C0C8D8)

$white1 = rgb(D8DEE9)
$white2 = rgb(E5E9F0)
$white3 = rgb(ECEFF4)

$blue0 = rgb(5E81AC)
$blue1 = rgb(81A1C1)
$blue2 = rgb(88C0D0)

$cyan_base = rgb(8FBCBB)
$cyan_bright = rgb(9FC6C5)
$cyan_dim = rgb(80B3B2)

$red_base = rgb(BF616A)
$red_bright = rgb(C5727A)
$red_dim = rgb(B74E58)

$orange_base = rgb(D08770)
$orange_bright = rgb(D79784)
$orange_dim = rgb(CB775D)

$yellow_base = rgb(EBCB8B)
$yellow_bright = rgb(EFD49F)
$yellow_dim = rgb(E7C173)

$green_base = rgb(A3BE8C)
$green_bright = rgb(B1C89D)
$green_dim = rgb(97B67C)

$magenta_base = rgb(B48EAD)
$magenta_bright = rgb(BE9DB8)
$magenta_dim = rgb(A97EA1)
