# monitor= desc:ASUSTek COMPUTER INC XG27ACS T1LMTF008132, 2560x1440@180.00Hz, 0x0, 1, cm, auto, vrr, 3, bitdepth, 8
monitorv2 {
    output = desc:ASUSTek COMPUTER INC XG27ACS T1LMTF008132
    mode = 2560x1440@180.00Hz
    position = 0x0
    scale = 1
    cm = auto
    vrr = 3
    bitdepth = 8
}

input {
    kb_model = pc104
    kb_layout = it
    kb_variant =
    kb_options = fkeys:basic_13-24 # caps:swapescape
    kb_rules =

    numlock_by_default = true

    repeat_rate = 30
    repeat_delay = 250

    follow_mouse = 1
    accel_profile = flat
    sensitivity = 0
}
